### ISSUE TITLE
Add autenficiation based on Devise

### ISSUE THREAD

**Issue by nemelnikov** [rails-up/expert#2]
Add autenficiation
Add field that distinct expert and inusers
Add profiles for both types of users

**Comment by vishaldeepak** [comment]
A good tutorial to get started - http://www.gotealeaf.com/blog/how-to-use-devise-in-rails-for-authentication

**Comment by nemelnikov** [comment]
Great work! But a little bit strange logic with routing.

**Comment by nemelnikov** [comment]
Do you plan to add ExpertProfile the same way?
